# docker-compose.yml文件的版本
version: '3.1'

# 管理的服务
services:
  redis:
    # 指定镜像
    image: erikdubbelboer/phpredisadmin:latest
    container_name: php-redis-admin
    # restart: always
    ports:
      # 端口映射
      - 8182:80
    environment:
      - REDIS_1_HOST=172.17.0.1
      - REDIS_1_PORT=16379
      # - REDIS_1_AUTH=redis@Dward#1234
      - REDIS_1_NAME=local

