# docker-compose.yml文件的版本
version: "3.1"
# 管理的服务
services:
  redis:
    # 指定镜像
    image: redis:7.0.5
    container_name: redis_7
    restart: always
    ports:
      # 端口映射
      - 16379:6379
    volumes:
      # 目录映射
      - "${PWD}/conf:/usr/local/etc/redis"
      - "${PWD}/data:/data"
    command:
      # 执行的命令
      redis-server
