version: "3.4"

networks:
  app_bridge:
    external: true

services:
  web:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    image: react-jblog-admin_image
    container_name: 'react-jblog-admin_container'
    environment:
      - NODE_ENV=production
    ports:
      - 8091:8091
    networks:
      - app_bridge
    volumes:
      - react-jblog-admin-data:/home/react-jblog-admin/dist
    restart: always

volumes:
  react-jblog-admin-data:
    driver: local
    external: true

